[server]
headless = true
address = "0.0.0.0"
port = 5000
enableXsrfProtection = true
enableCORS = false
maxUploadSize = 200
maxMessageSize = 200
runOnSave = true

[theme]
primaryColor = "#0066FF"
backgroundColor = "#1E1E1E"
secondaryBackgroundColor = "#252525"
textColor = "#FFFFFF"
font = "Inter"

[browser]
serverAddress = "0.0.0.0"
serverPort = 5000
gatherUsageStats = false